import type { Book } from "../Models/Book";

import img1 from "../assets/img/product-item1.jpg";
import img2 from "../assets/img/product-item2.jpg";
import img3 from "../assets/img/product-item3.jpg";
import img4 from "../assets/img/product-item4.jpg";
import img5 from "../assets/img/product-item5.jpg";
import img6 from "../assets/img/product-item6.jpg";
import img7 from "../assets/img/product-item7.jpg";
import img8 from "../assets/img/product-item8.jpg";
import img9 from "../assets/img/tab-item1.jpg";
import img10 from "../assets/img/tab-item2.jpg";
import img11 from "../assets/img/tab-item3.jpg";
import img12 from "../assets/img/tab-item4.jpg";
import img13 from "../assets/img/tab-item5.jpg";
import img14 from "../assets/img/tab-item6.jpg";
import img15 from "../assets/img/tab-item7.jpg";
import img16 from "../assets/img/tab-item8.jpg";

export const ALL_BOOKS: Book[] = [
  {
    id: "1",
    title: "Simple Way Of Piece Life",
    author: "Armor Ramsey",
    description: "",
    categories: ["Business"],
    price: 40,
    oldPrice: undefined,
    inStock: true,
    createdAt: "2024-01-01T00:00:00Z",
    imageUrl: img1,
  },
  {
    id: "2",
    title: "Great Travel At Desert",
    author: "Sanchit Howdy",
    description: "",
    categories: ["Adventure"],
    price: 38,
    oldPrice: undefined,
    inStock: true,
    createdAt: "2024-01-02T00:00:00Z",
    imageUrl: img2,
  },
  {
    id: "3",
    title: "The Lady Beauty Scarlett",
    author: "Arthur Doyle",
    description: "",
    categories: ["Romantic"],
    price: 45,
    oldPrice: undefined,
    inStock: true,
    createdAt: "2024-01-03T00:00:00Z",
    imageUrl: img3,
  },
  {
    id: "4",
    title: "Once Upon A Time",
    author: "Klien Marry",
    description: "",
    categories: ["Fictional"],
    price: 35,
    oldPrice: undefined,
    inStock: true,
    createdAt: "2024-01-04T00:00:00Z",
    imageUrl: img4,
  },
  {
    id: "5",
    title: "The Creative Eye",
    author: "Lisa Hart",
    description: "",
    categories: [],
    price: 25,
    oldPrice: 40,
    inStock: true,
    createdAt: "2024-01-05T00:00:00Z",
    imageUrl: img5,
  },
  {
    id: "6",
    title: "Mindful Days",
    author: "Paul Grant",
    description: "",
    categories: [],
    price: 30,
    oldPrice: 50,
    inStock: true,
    createdAt: "2024-01-06T00:00:00Z",
    imageUrl: img6,
  },
  {
    id: "7",
    title: "Digital Dreams",
    author: "Sophie Lee",
    description: "",
    categories: [],
    price: 20,
    oldPrice: 35,
    inStock: true,
    createdAt: "2024-01-07T00:00:00Z",
    imageUrl: img7,
  },
  {
    id: "8",
    title: "The Silent Hour",
    author: "George Miles",
    description: "",
    categories: [],
    price: 28,
    oldPrice: 42,
    inStock: true,
    createdAt: "2024-01-08T00:00:00Z",
    imageUrl: img8,
  },
  {
    id: "9",
    title: "Winds of Wisdom",
    author: "Anna Bright",
    description: "",
    categories: [],
    price: 22,
    oldPrice: 38,
    inStock: true,
    createdAt: "2024-01-09T00:00:00Z",
    imageUrl: img9,
  },
  {
    id: "10",
    title: "Night Sky Chronicles",
    author: "Tom Ryder",
    description: "",
    categories: [],
    price: 27,
    oldPrice: 45,
    inStock: true,
    createdAt: "2024-01-10T00:00:00Z",
    imageUrl: img10,
  },
  {
    id: "11",
    title: "Night Sky Chronicles",
    author: "Tom Ryder",
    description: "",
    categories: [],
    price: 27,
    oldPrice: 45,
    inStock: true,
    createdAt: "2024-01-10T00:00:00Z",
    imageUrl: img11,
  },
  {
    id: "12",
    title: "Night Sky Chronicles",
    author: "Tom Ryder",
    description: "",
    categories: [],
    price: 27,
    oldPrice: 45,
    inStock: true,
    createdAt: "2024-01-10T00:00:00Z",
    imageUrl: img12,
  },
  {
    id: "13",
    title: "Night Sky Chronicles",
    author: "Tom Ryder",
    description: "",
    categories: [],
    price: 27,
    oldPrice: 45,
    inStock: true,
    createdAt: "2024-01-10T00:00:00Z",
    imageUrl: img13,
  },
  {
    id: "14",
    title: "Night Sky Chronicles",
    author: "Tom Ryder",
    description: "",
    categories: [],
    price: 27,
    oldPrice: 45,
    inStock: true,
    createdAt: "2024-01-10T00:00:00Z",
    imageUrl: img14,
  },
  {
    id: "15",
    title: "Night Sky Chronicles",
    author: "Tom Ryder",
    description: "",
    categories: [],
    price: 27,
    oldPrice: 45,
    inStock: true,
    createdAt: "2024-01-10T00:00:00Z",
    imageUrl: img15,
  },
  {
    id: "16",
    title: "Night Sky Chronicles",
    author: "Tom Ryder",
    description: "",
    categories: [],
    price: 27,
    oldPrice: 45,
    inStock: true,
    createdAt: "2024-01-10T00:00:00Z",
    imageUrl: img16,
  },
];
